### ISSUE TITLE
Add README with link to the web dev github pages

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web_dev#1]

**Comment by grzanka** [comment]
Do you see readme on main page ? https://github.com/libamtrack/web_dev

**Comment by adudzik** [comment]
I think every deploy remove all previous content. We should create for example `gh-pages` branch where we will deploy application. On `master`, there will be only readme. @marwin1991, what do you think?

**Comment by marwin1991** [comment]
I think it is good idea

**Comment by marwin1991** [comment]
now travis-bot commit to gh-pages brunch, @adudzik can you add once again readme and remove other files from master?

**Comment by adudzik** [comment]
I think it's done. Now readme should be always visible on master.
