### ISSUE TITLE
Check if deployment works correctly

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web_dev#3]
![image](https://user-images.githubusercontent.com/7374733/49814638-5a692100-fd6a-11e8-9259-8d9542729804.png)

Above is what I see when visiting https://libamtrack.github.io/web_dev/

But travis seems to deploy my changes: 
 - https://travis-ci.org/libamtrack/web/builds/466594336
which are visible in the repo:
 - https://github.com/libamtrack/web_dev/tree/gh-pages

is there some delay of GH pages to render the page ?

**Comment by marwin1991** [comment]
Sometimes there is a bug that changes wont appeare on the gh-pages

**Comment by marwin1991** [comment]
Or there is some other problem i am checking that

**Comment by marwin1991** [comment]
okay i found a problem that two componets had the same name and it produced error in main page that now should not appear. Maybe when is error in main page gh-pages wont change?

**Comment by marwin1991** [comment]
But still pages wont change

**Comment by marwin1991** [comment]
i run a depoly from command line on this repo and it works so maybe there is some github problem.

**Comment by marwin1991** [comment]
oh also https://libamtrack.github.io/web_dev/ are changes now avaliable. but i had to use incognito mode. Probably chrome do some nice optymalization.

**Comment by grzanka** [comment]
Seems ok now
